#!/usr/bin/env bash

status() {
  echo "-----> $*"
}

# sed -l basically makes sed replace and buffer through stdin to stdout
# so you get updates while the command runs and dont wait for the end
# e.g. npm install | indent
indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";; # mac/bsd sed: -l buffers on line boundaries
    *)      sed -u "$c";; # unix/gnu sed: -u unbuffered (arbitrary) chunks of data
  esac
}

function install_gems() {
  cache_dir=$1
  gems=$2

  rm -rf "${cache_dir}/.gems" && mkdir -p "${cache_dir}/.gems"

  gem install --no-rdoc --no-ri -i "${cache_dir}/.gems" ${gems} 2>&1 | indent

  export PATH="${cache_dir}/.gems/bin:${PATH}"
  export GEM_PATH="${cache_dir}/.gems:${GEM_PATH}"
}
